insert into public.menu_items (name, description, category, price, image_url, ingredients, allergens, dietary_tags, taste_profile_tags, spice_level, availability_status)
values
('Mushroom Soup', 'Creamy mushroom soup with herbs and garlic croutons.', 'Starters', 110, 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80', array['mushroom','cream','garlic','onion','herbs'], array['Dairy'], array['Vegetarian'], array['Savory','Mild'], 'None', 'available'),
('Halloumi & Pear Salad', 'Grilled halloumi with fresh greens, sliced pear, toasted nuts, and balsamic glaze.', 'Starters', 120, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80', array['halloumi','pear','mixed greens','nuts','balsamic'], array['Dairy','Nuts'], array['Vegetarian'], array['Light','Savory'], 'None', 'available'),
('Arrabbiata Tagliatelle', 'Fresh handmade pasta with spicy tomato sauce, chili flakes, garlic, and basil.', 'Main Courses', 120, 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80', array['pasta','tomato','garlic','chili','basil'], array['Gluten'], array['Vegetarian'], array['Spicy','Savory'], 'Medium', 'available'),
('Herb Encrusted Salmon', 'Grilled salmon with herb crust, roasted vegetables, and lemon butter.', 'Main Courses', 260, 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?auto=format&fit=crop&w=900&q=80', array['salmon','herbs','butter','lemon','vegetables'], array['Fish','Dairy'], array['High Protein'], array['Savory','Fresh'], 'Mild', 'available'),
('Garlic Bread', 'Toasted bread with garlic butter, parsley, and sea salt.', 'Starters', 90, 'https://images.unsplash.com/photo-1573140401552-3fab0b24306f?auto=format&fit=crop&w=900&q=80', array['bread','garlic','butter','parsley'], array['Gluten','Dairy'], array['Vegetarian'], array['Savory'], 'None', 'sold_out'),
('Lime & Mint Sparkle', 'Refreshing sour lime drink with mint and sparkling water.', 'Drinks', 60, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80', array['lime','mint','sparkling water','sugar'], array[]::text[], array['Vegan'], array['Sour','Refreshing'], 'None', 'available')
on conflict do nothing;
